{{- if .Values.buildkit.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "github-runner.fullname" . }}-buildkitd
  labels:
    {{- include "github-runner.labels" . | nindent 4 }}
data:
  buildkitd.toml: |
    {{- range .Values.buildkit.insecureRegistries }}
    [registry."{{ . }}"]
      http = true
      insecure = true
    {{- end }}
{{- end }}
