apiVersion: v1
entries:
  chaos-mesh:
  - annotations:
      artifacthub.io/containsSecurityUpdates: "false"
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
      artifacthub.io/operatorCapabilities: Seamless Upgrades
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 2.8.1
    created: "2026-02-10T16:37:02.248620846Z"
    description: Chaos Mesh is a cloud-native Chaos Engineering platform that orchestrates
      chaos on Kubernetes environments.
    digest: 27d3411c18c15eb55e40b4c5255a06d7a6f8d97b722f58faae0255fe5c894f4b
    home: https://chaos-mesh.org
    icon: https://raw.githubusercontent.com/chaos-mesh/chaos-mesh/master/static/logo.svg
    keywords:
    - chaos-engineering
    - resiliency
    - fault-injection
    - kubernetes
    - testing
    maintainers:
    - email: cwen@pingcap.com
      name: cwen0
    - email: yangkeao@chunibyo.icu
      name: YangKeao
    - email: wenghao@pingcap.com
      name: dcalvin
    - email: yb532204897@gmail.com
      name: yeya24
    - email: tttick@gmail.com
      name: Gallardot
    name: chaos-mesh
    sources:
    - https://github.com/chaos-mesh/chaos-mesh
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/chaos-mesh-2.8.1.tgz
    version: 2.8.1
  dapr:
  - apiVersion: v2
    appVersion: 1.16.8
    created: "2026-02-10T16:37:02.261919589Z"
    dependencies:
    - name: dapr_rbac
      repository: file://dapr_rbac
      version: 1.16.8
    - name: dapr_operator
      repository: file://dapr_operator
      version: 1.16.8
    - name: dapr_placement
      repository: file://dapr_placement
      version: 1.16.8
    - name: dapr_sidecar_injector
      repository: file://dapr_sidecar_injector
      version: 1.16.8
    - name: dapr_sentry
      repository: file://dapr_sentry
      version: 1.16.8
    - name: dapr_scheduler
      repository: file://dapr_scheduler
      version: 1.16.8
    - name: dapr_config
      repository: file://dapr_config
      version: 1.16.8
    description: A Helm chart for Dapr on Kubernetes
    digest: 143d414dedcde4c46b0c49352703115e5a78006202f1776a41d8efec1950b92f
    icon: https://dapr.io/images/dapr.svg
    name: dapr
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/dapr-1.16.8.tgz
    version: 1.16.8
  k6-operator:
  - apiVersion: v1
    appVersion: 1.2.0
    created: "2026-02-10T16:37:02.273506698Z"
    description: A Helm chart to install the k6-operator
    digest: 59092761e2fdd26c4069a87b3953b1963be5a6d369b91d09a0f092e37b22be17
    home: https://k6.io
    icon: https://raw.githubusercontent.com/grafana/k6-docs/main/static/images/icon.png
    keywords:
    - load-testing
    - smoke-testing
    - stress-testing
    - soak-testing
    - kubernetes
    - distributed-testing
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: olha@k6.io
      name: yorugac
    name: k6-operator
    sources:
    - https://github.com/grafana/k6-operator
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/k6-operator-4.2.0.tgz
    version: 4.2.0
  k8s-monitoring:
  - apiVersion: v2
    appVersion: 3.8.0
    created: "2026-02-10T16:37:02.389304175Z"
    dependencies:
    - alias: annotationAutodiscovery
      condition: annotationAutodiscovery.enabled
      name: feature-annotation-autodiscovery
      repository: ""
      version: 1.0.0
    - alias: applicationObservability
      condition: applicationObservability.enabled
      name: feature-application-observability
      repository: ""
      version: 1.0.0
    - alias: autoInstrumentation
      condition: autoInstrumentation.enabled
      name: feature-auto-instrumentation
      repository: ""
      version: 1.0.0
    - alias: clusterEvents
      condition: clusterEvents.enabled
      name: feature-cluster-events
      repository: ""
      version: 1.0.0
    - alias: clusterMetrics
      condition: clusterMetrics.enabled
      name: feature-cluster-metrics
      repository: ""
      version: 1.0.0
    - alias: integrations
      name: feature-integrations
      repository: ""
      version: 1.0.0
    - alias: nodeLogs
      condition: nodeLogs.enabled
      name: feature-node-logs
      repository: ""
      version: 1.0.0
    - alias: podLogs
      condition: podLogs.enabled
      name: feature-pod-logs
      repository: ""
      version: 1.0.0
    - alias: podLogsViaKubernetesApi
      condition: podLogsViaKubernetesApi.enabled
      name: feature-pod-logs-via-kubernetes-api
      repository: ""
      version: 1.0.0
    - alias: podLogsObjects
      condition: podLogsObjects.enabled
      name: feature-pod-logs-objects
      repository: ""
      version: 1.0.0
    - alias: profiling
      condition: profiling.enabled
      name: feature-profiling
      repository: ""
      version: 1.0.0
    - alias: profilesReceiver
      condition: profilesReceiver.enabled
      name: feature-profiles-receiver
      repository: ""
      version: 1.0.0
    - alias: prometheusOperatorObjects
      condition: prometheusOperatorObjects.enabled
      name: feature-prometheus-operator-objects
      repository: ""
      version: 1.0.0
    - condition: alloy-operator.deploy
      name: alloy-operator
      repository: https://grafana.github.io/helm-charts
      version: 0.4.1
    description: Capture all telemetry data from your Kubernetes cluster.
    digest: d8c41cb86a41ca212e81f5d1e98b42ccbf223c8d9d8b2531d170c45e4e140a64
    icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
    maintainers:
    - email: pete.wall@grafana.com
      name: petewall
    - email: robert.lankford@grafana.com
      name: rlankfo
    name: k8s-monitoring
    sources:
    - https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring
    type: application
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/k8s-monitoring-3.8.0.tgz
    version: 3.8.0
  mathtrail-service-lib:
  - apiVersion: v2
    created: "2026-02-10T16:37:02.400762841Z"
    description: 'Library Helm Chart for MathTrail microservices. Provides reusable
      templates. '
    digest: 724ab1d63781f217df02b737c7101603057580b4439bbd2bd4fe1c033f2a90f1
    name: mathtrail-service-lib
    type: library
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/mathtrail-service-lib-0.1.0.tgz
    version: 0.1.0
  opentelemetry-collector:
  - apiVersion: v2
    appVersion: 0.145.0
    created: "2026-02-10T16:37:02.412652036Z"
    description: OpenTelemetry Collector Helm chart for Kubernetes
    digest: 6fcc59ac0d48edf35122994a707929c97ad8c26baf4161b3ac5460adf163bac8
    home: https://opentelemetry.io/
    icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
    maintainers:
    - name: dmitryax
    - name: jaronoff97
    - name: TylerHelmuth
    name: opentelemetry-collector
    sources:
    - https://github.com/open-telemetry/opentelemetry-collector
    - https://github.com/open-telemetry/opentelemetry-collector-contrib
    type: application
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/opentelemetry-collector-0.145.0.tgz
    version: 0.145.0
  postgresql:
  - annotations:
      fips: "true"
      images: |
        - name: os-shell
          version: "5"
          image: registry-1.docker.io/bitnami/os-shell:latest
        - name: postgres-exporter
          version: 0.19.0
          image: registry-1.docker.io/bitnami/postgres-exporter:latest
        - name: postgresql
          version: 18.1.0
          image: registry-1.docker.io/bitnami/postgresql:latest
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 18.1.0
    created: "2026-02-10T16:37:02.455955351Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.36.0
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: edc93add5c259f28c0c19ec471c430a68bd9703ca7bf2f13286666dcacbc732b
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/postgresql-18.2.6.tgz
    version: 18.2.6
  - annotations:
      fips: "true"
      images: |
        - name: os-shell
          version: "5"
          image: registry-1.docker.io/bitnami/os-shell:latest
        - name: postgres-exporter
          version: 0.18.1
          image: registry-1.docker.io/bitnami/postgres-exporter:latest
        - name: postgresql
          version: 18.1.0
          image: registry-1.docker.io/bitnami/postgresql:latest
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 18.1.0
    created: "2026-02-10T16:37:02.434528657Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.34.0
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: bf7b4c08d8e31f3f9e53f103d4f354425d4c7a5b968677af209bbca88d5a16bf
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/postgresql-18.2.4.tgz
    version: 18.2.4
  pyroscope:
  - apiVersion: v2
    appVersion: 1.18.0
    created: "2026-02-10T16:37:02.48592593Z"
    dependencies:
    - alias: agent
      condition: agent.enabled
      name: grafana-agent
      repository: https://grafana.github.io/helm-charts
      version: 0.44.2
    - alias: alloy
      condition: alloy.enabled
      name: alloy
      repository: https://grafana.github.io/helm-charts
      version: 1.5.2
    - alias: minio
      condition: minio.enabled
      name: minio
      repository: https://charts.min.io/
      version: 4.1.0
    description: "\U0001F525 horizontally-scalable, highly-available, multi-tenant
      continuous profiling aggregation system"
    digest: e6b04ee6c05e6a6b33796cc3c46426710d68e2ed7dedfc53cee369048e75bef0
    home: https://grafana.com/oss/pyroscope/
    name: pyroscope
    sources:
    - https://github.com/grafana/pyroscope
    - https://github.com/grafana/pyroscope/tree/main/operations/pyroscope/helm/pyroscope
    type: application
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/pyroscope-1.18.1.tgz
    version: 1.18.1
  redis:
  - annotations:
      fips: "true"
      images: |
        - name: kubectl
          version: 1.35.0
          image: registry-1.docker.io/bitnami/kubectl:latest
        - name: os-shell
          version: "5"
          image: registry-1.docker.io/bitnami/os-shell:latest
        - name: redis
          version: 8.4.1
          image: registry-1.docker.io/bitnami/redis:latest
        - name: redis-exporter
          version: 1.80.2
          image: registry-1.docker.io/bitnami/redis-exporter:latest
        - name: redis-sentinel
          version: 8.4.1
          image: registry-1.docker.io/bitnami/redis-sentinel:latest
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 8.4.1
    created: "2026-02-10T16:37:02.535671813Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.36.0
    description: Redis(R) is an open source, advanced key-value store. It is often
      referred to as a data structure server since keys can contain strings, hashes,
      lists, sets and sorted sets.
    digest: 6e3ca55e761c1e4c45c998220e68ab73607bc7678a4b3affbc78b5fc4ed0a4c6
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: redis
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/redis
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/redis-24.1.8.tgz
    version: 24.1.8
  - annotations:
      fips: "true"
      images: |
        - name: kubectl
          version: 1.35.0
          image: registry-1.docker.io/bitnami/kubectl:latest
        - name: os-shell
          version: "5"
          image: registry-1.docker.io/bitnami/os-shell:latest
        - name: redis
          version: 8.4.1
          image: registry-1.docker.io/bitnami/redis:latest
        - name: redis-exporter
          version: 1.80.2
          image: registry-1.docker.io/bitnami/redis-exporter:latest
        - name: redis-sentinel
          version: 8.4.1
          image: registry-1.docker.io/bitnami/redis-sentinel:latest
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 8.4.1
    created: "2026-02-10T16:37:02.512425653Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.34.0
    description: Redis(R) is an open source, advanced key-value store. It is often
      referred to as a data structure server since keys can contain strings, hashes,
      lists, sets and sorted sets.
    digest: e1db7d452a1d40ec905e9fa742914074873686c32c0d56bd71ff168fb0c8bbcb
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: redis
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/redis
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/redis-24.1.6.tgz
    version: 24.1.6
  strimzi-kafka-operator:
  - apiVersion: v2
    appVersion: 0.50.0
    created: "2026-02-10T16:37:02.566350449Z"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: 3dff5a4947584f4d124a701f28df180f7dd6a8bf4c963f7f375fdb28527059af
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - email: cncf-strimzi-maintainers@lists.cncf.io
      name: Strimzi Project Maintainers
      url: https://github.com/strimzi/governance
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/strimzi-kafka-operator-helm-3-chart-0.50.0.tgz
    version: 0.50.0
  telepresence:
  - apiVersion: v2
    appVersion: 2.20.2
    created: "2026-02-10T16:37:02.576692213Z"
    dependencies:
    - condition: ambassador-agent.enabled
      name: ambassador-agent
      repository: https://app.getambassador.io/
      version: ~1.0.0
    description: A chart for deploying the server-side components of Telepresence
    digest: 6a4f8ebbc10948425c751c865112b26f07302f64e3483f0b375602e07c273cef
    icon: https://www.getambassador.io/images/logo.png
    name: telepresence
    type: application
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/telepresence-2.20.2.tgz
    version: 2.20.2
generated: "2026-02-10T16:37:02.190987876Z"
