apiVersion: v1
entries:
  dapr:
  - apiVersion: v2
    appVersion: 1.16.8
    created: "2026-02-07T19:13:55.6365206-06:00"
    dependencies:
    - name: dapr_rbac
      repository: file://dapr_rbac
      version: 1.16.8
    - name: dapr_operator
      repository: file://dapr_operator
      version: 1.16.8
    - name: dapr_placement
      repository: file://dapr_placement
      version: 1.16.8
    - name: dapr_sidecar_injector
      repository: file://dapr_sidecar_injector
      version: 1.16.8
    - name: dapr_sentry
      repository: file://dapr_sentry
      version: 1.16.8
    - name: dapr_scheduler
      repository: file://dapr_scheduler
      version: 1.16.8
    - name: dapr_config
      repository: file://dapr_config
      version: 1.16.8
    description: A Helm chart for Dapr on Kubernetes
    digest: 143d414dedcde4c46b0c49352703115e5a78006202f1776a41d8efec1950b92f
    icon: https://dapr.io/images/dapr.svg
    name: dapr
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/dapr-1.16.8.tgz
    version: 1.16.8
  k6-operator:
  - apiVersion: v1
    appVersion: 1.2.0
    created: "2026-02-07T19:13:55.6431986-06:00"
    description: A Helm chart to install the k6-operator
    digest: 59092761e2fdd26c4069a87b3953b1963be5a6d369b91d09a0f092e37b22be17
    home: https://k6.io
    icon: https://raw.githubusercontent.com/grafana/k6-docs/main/static/images/icon.png
    keywords:
    - load-testing
    - smoke-testing
    - stress-testing
    - soak-testing
    - kubernetes
    - distributed-testing
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: olha@k6.io
      name: yorugac
    name: k6-operator
    sources:
    - https://github.com/grafana/k6-operator
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/k6-operator-4.2.0.tgz
    version: 4.2.0
  postgresql:
  - annotations:
      fips: "true"
      images: |
        - name: os-shell
          version: "5"
          image: registry-1.docker.io/bitnami/os-shell:latest
        - name: postgres-exporter
          version: 0.18.1
          image: registry-1.docker.io/bitnami/postgres-exporter:latest
        - name: postgresql
          version: 18.1.0
          image: registry-1.docker.io/bitnami/postgresql:latest
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 18.1.0
    created: "2026-02-07T19:13:55.6665161-06:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.34.0
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: bf7b4c08d8e31f3f9e53f103d4f354425d4c7a5b968677af209bbca88d5a16bf
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/postgresql-18.2.4.tgz
    version: 18.2.4
  redis:
  - annotations:
      fips: "true"
      images: |
        - name: kubectl
          version: 1.35.0
          image: registry-1.docker.io/bitnami/kubectl:latest
        - name: os-shell
          version: "5"
          image: registry-1.docker.io/bitnami/os-shell:latest
        - name: redis
          version: 8.4.0
          image: registry-1.docker.io/bitnami/redis:latest
        - name: redis-exporter
          version: 1.80.2
          image: registry-1.docker.io/bitnami/redis-exporter:latest
        - name: redis-sentinel
          version: 8.4.0
          image: registry-1.docker.io/bitnami/redis-sentinel:latest
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 8.4.0
    created: "2026-02-07T19:13:55.6893892-06:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.34.0
    description: Redis(R) is an open source, advanced key-value store. It is often
      referred to as a data structure server since keys can contain strings, hashes,
      lists, sets and sorted sets.
    digest: 50673893ab5f558dcae05184594627313aae23063b86eec68a8c3615b4bf2c34
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: redis
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/redis
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/redis-24.1.3.tgz
    version: 24.1.3
  strimzi-kafka-operator:
  - apiVersion: v2
    appVersion: 0.50.0
    created: "2026-02-07T19:13:55.7177639-06:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: 3dff5a4947584f4d124a701f28df180f7dd6a8bf4c963f7f375fdb28527059af
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - email: cncf-strimzi-maintainers@lists.cncf.io
      name: Strimzi Project Maintainers
      url: https://github.com/strimzi/governance
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - https://RyazanovAlexander.github.io/mathtrail-charts/charts/strimzi-kafka-operator-helm-3-chart-0.50.0.tgz
    version: 0.50.0
generated: "2026-02-07T19:13:55.6157193-06:00"
