apiVersion: v1
entries:
  chaos-mesh:
  - annotations:
      artifacthub.io/containsSecurityUpdates: "false"
      artifacthub.io/license: Apache-2.0
      artifacthub.io/operator: "true"
      artifacthub.io/operatorCapabilities: Seamless Upgrades
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 2.8.1
    created: "2026-02-15T22:50:19.019393059Z"
    description: Chaos Mesh is a cloud-native Chaos Engineering platform that orchestrates
      chaos on Kubernetes environments.
    digest: 27d3411c18c15eb55e40b4c5255a06d7a6f8d97b722f58faae0255fe5c894f4b
    home: https://chaos-mesh.org
    icon: https://raw.githubusercontent.com/chaos-mesh/chaos-mesh/master/static/logo.svg
    keywords:
    - chaos-engineering
    - resiliency
    - fault-injection
    - kubernetes
    - testing
    maintainers:
    - email: cwen@pingcap.com
      name: cwen0
    - email: yangkeao@chunibyo.icu
      name: YangKeao
    - email: wenghao@pingcap.com
      name: dcalvin
    - email: yb532204897@gmail.com
      name: yeya24
    - email: tttick@gmail.com
      name: Gallardot
    name: chaos-mesh
    sources:
    - https://github.com/chaos-mesh/chaos-mesh
    urls:
    - https://MathTrail.github.io/charts/charts/chaos-mesh-2.8.1.tgz
    version: 2.8.1
  dapr:
  - apiVersion: v2
    appVersion: 1.16.9
    created: "2026-02-15T22:50:19.043570518Z"
    dependencies:
    - name: dapr_rbac
      repository: file://dapr_rbac
      version: 1.16.9
    - name: dapr_operator
      repository: file://dapr_operator
      version: 1.16.9
    - name: dapr_placement
      repository: file://dapr_placement
      version: 1.16.9
    - name: dapr_sidecar_injector
      repository: file://dapr_sidecar_injector
      version: 1.16.9
    - name: dapr_sentry
      repository: file://dapr_sentry
      version: 1.16.9
    - name: dapr_scheduler
      repository: file://dapr_scheduler
      version: 1.16.9
    - name: dapr_config
      repository: file://dapr_config
      version: 1.16.9
    description: A Helm chart for Dapr on Kubernetes
    digest: dd0a5fe4ecfb87b89af2ba832687dce111bfb61497e28b1247bee75e5251593e
    icon: https://dapr.io/images/dapr.svg
    name: dapr
    urls:
    - https://MathTrail.github.io/charts/charts/dapr-1.16.9.tgz
    version: 1.16.9
  github-runner:
  - apiVersion: v2
    appVersion: latest
    created: "2026-02-15T22:50:19.059124541Z"
    description: GitHub Actions self-hosted runner for MathTrail CI/CD (BuildKit +
      Buildah)
    digest: 78b4fc1a3b6363bebaac86d6ca87098d578da94e5e8792b183b40662dd06d9c4
    name: github-runner
    type: application
    urls:
    - https://MathTrail.github.io/charts/charts/github-runner-0.2.6.tgz
    version: 0.2.6
  hydra:
  - apiVersion: v2
    appVersion: v25.4.0
    created: "2026-02-15T22:50:19.076155278Z"
    dependencies:
    - alias: ory
      name: ory-commons
      repository: file://../ory-commons
      version: 0.1.0
    - alias: hydra-maester
      condition: maester.enabled
      name: hydra-maester
      repository: file://../hydra-maester
      version: 0.60.1
    description: A Helm chart for deploying ORY Hydra in Kubernetes
    digest: 27c6d43c3c35798f7434ff51875e4f538601b3dcf06fff0ad03a53670fc3d294
    home: https://www.ory.sh/
    icon: https://raw.githubusercontent.com/ory/docs/master/docs/static/img/logo-hydra.svg
    keywords:
    - oauth2
    - openid-connect
    - openid
    - oidc
    - op
    - api-security
    - security
    maintainers:
    - email: hi@ory.sh
      name: ORY Team
      url: https://www.ory.sh/
    name: hydra
    sources:
    - https://github.com/ory/hydra
    - https://github.com/ory/k8s
    type: application
    urls:
    - https://MathTrail.github.io/charts/charts/hydra-0.60.1.tgz
    version: 0.60.1
  k6-operator:
  - apiVersion: v1
    appVersion: 1.2.0
    created: "2026-02-15T22:50:19.091156079Z"
    description: A Helm chart to install the k6-operator
    digest: 59092761e2fdd26c4069a87b3953b1963be5a6d369b91d09a0f092e37b22be17
    home: https://k6.io
    icon: https://raw.githubusercontent.com/grafana/k6-docs/main/static/images/icon.png
    keywords:
    - load-testing
    - smoke-testing
    - stress-testing
    - soak-testing
    - kubernetes
    - distributed-testing
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: olha@k6.io
      name: yorugac
    name: k6-operator
    sources:
    - https://github.com/grafana/k6-operator
    urls:
    - https://MathTrail.github.io/charts/charts/k6-operator-4.2.0.tgz
    version: 4.2.0
  k8s-monitoring:
  - apiVersion: v2
    appVersion: 3.8.0
    created: "2026-02-15T22:50:19.251254552Z"
    dependencies:
    - alias: annotationAutodiscovery
      condition: annotationAutodiscovery.enabled
      name: feature-annotation-autodiscovery
      repository: ""
      version: 1.0.0
    - alias: applicationObservability
      condition: applicationObservability.enabled
      name: feature-application-observability
      repository: ""
      version: 1.0.0
    - alias: autoInstrumentation
      condition: autoInstrumentation.enabled
      name: feature-auto-instrumentation
      repository: ""
      version: 1.0.0
    - alias: clusterEvents
      condition: clusterEvents.enabled
      name: feature-cluster-events
      repository: ""
      version: 1.0.0
    - alias: clusterMetrics
      condition: clusterMetrics.enabled
      name: feature-cluster-metrics
      repository: ""
      version: 1.0.0
    - alias: integrations
      name: feature-integrations
      repository: ""
      version: 1.0.0
    - alias: nodeLogs
      condition: nodeLogs.enabled
      name: feature-node-logs
      repository: ""
      version: 1.0.0
    - alias: podLogs
      condition: podLogs.enabled
      name: feature-pod-logs
      repository: ""
      version: 1.0.0
    - alias: podLogsViaKubernetesApi
      condition: podLogsViaKubernetesApi.enabled
      name: feature-pod-logs-via-kubernetes-api
      repository: ""
      version: 1.0.0
    - alias: podLogsObjects
      condition: podLogsObjects.enabled
      name: feature-pod-logs-objects
      repository: ""
      version: 1.0.0
    - alias: profiling
      condition: profiling.enabled
      name: feature-profiling
      repository: ""
      version: 1.0.0
    - alias: profilesReceiver
      condition: profilesReceiver.enabled
      name: feature-profiles-receiver
      repository: ""
      version: 1.0.0
    - alias: prometheusOperatorObjects
      condition: prometheusOperatorObjects.enabled
      name: feature-prometheus-operator-objects
      repository: ""
      version: 1.0.0
    - condition: alloy-operator.deploy
      name: alloy-operator
      repository: https://grafana.github.io/helm-charts
      version: 0.4.1
    description: Capture all telemetry data from your Kubernetes cluster.
    digest: d8c41cb86a41ca212e81f5d1e98b42ccbf223c8d9d8b2531d170c45e4e140a64
    icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
    maintainers:
    - email: pete.wall@grafana.com
      name: petewall
    - email: robert.lankford@grafana.com
      name: rlankfo
    name: k8s-monitoring
    sources:
    - https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring
    type: application
    urls:
    - https://MathTrail.github.io/charts/charts/k8s-monitoring-3.8.0.tgz
    version: 3.8.0
  keto:
  - apiVersion: v2
    appVersion: v25.4.0
    created: "2026-02-15T22:50:19.268167797Z"
    dependencies:
    - alias: ory
      name: ory-commons
      repository: file://../ory-commons
      version: 0.1.0
    description: Access Control Policies as a Server
    digest: 3a55d795e56c04f8820de28bca22c3181dbb6c2bddfe1321e5e6285c6beeacce
    home: https://www.ory.sh/keto/
    icon: https://raw.githubusercontent.com/ory/docs/master/docs/static/img/logo-keto.svg
    keywords:
    - rbac
    - hrbac
    - acl
    - iam
    - api-security
    - security
    maintainers:
    - email: hi@ory.sh
      name: ORY Team
      url: https://www.ory.sh/
    name: keto
    sources:
    - https://github.com/ory/keto
    - https://github.com/ory/k8s
    type: application
    urls:
    - https://MathTrail.github.io/charts/charts/keto-0.60.1.tgz
    version: 0.60.1
  kratos:
  - apiVersion: v2
    appVersion: v25.4.0
    created: "2026-02-15T22:50:19.288476915Z"
    dependencies:
    - alias: ory
      name: ory-commons
      repository: file://../ory-commons
      version: 0.1.0
    description: A ORY Kratos Helm chart for Kubernetes
    digest: b576e2aa4218b456ca44c16156115e172d40b4c82fa9009f5c50fc3a6bcf9dd2
    icon: https://raw.githubusercontent.com/ory/docs/master/docs/static/img/logo-kratos.svg
    name: kratos
    type: application
    urls:
    - https://MathTrail.github.io/charts/charts/kratos-0.60.1.tgz
    version: 0.60.1
  mathtrail-service-lib:
  - apiVersion: v2
    created: "2026-02-15T22:50:19.303171319Z"
    description: 'Library Helm Chart for MathTrail microservices. Provides reusable
      templates. '
    digest: 084e3e11c79a130c8e6fd1c4c7e8447d9ff08022d0d048be3e63784183d59ba7
    name: mathtrail-service-lib
    type: library
    urls:
    - https://MathTrail.github.io/charts/charts/mathtrail-service-lib-0.1.1.tgz
    version: 0.1.1
  oathkeeper:
  - apiVersion: v2
    appVersion: v25.4.0
    created: "2026-02-15T22:50:19.316642895Z"
    dependencies:
    - alias: oathkeeper-maester
      condition: maester.enabled
      name: oathkeeper-maester
      repository: file://../oathkeeper-maester
      version: 0.60.1
    description: A Helm chart for deploying ORY Oathkeeper in Kubernetes
    digest: c9a32f981f78908524460e6e2fdac31b3a4d2961b6299468e94b25f883e4953b
    home: https://www.ory.sh/
    icon: https://raw.githubusercontent.com/ory/docs/master/docs/static/img/logo-oathkeeper.svg
    keywords:
    - zero-trust
    - beyond-corp
    - access-control
    - reverse-proxy
    - nginx
    - envoy
    - ambassador
    - auth-filter
    maintainers:
    - email: office@ory.sh
      name: ORY Team
      url: https://www.ory.sh/
    name: oathkeeper
    sources:
    - https://github.com/ory/oathkeeper
    - https://github.com/ory/k8s
    type: application
    urls:
    - https://MathTrail.github.io/charts/charts/oathkeeper-0.60.1.tgz
    version: 0.60.1
  opentelemetry-collector:
  - apiVersion: v2
    appVersion: 0.145.0
    created: "2026-02-15T22:50:19.333159941Z"
    description: OpenTelemetry Collector Helm chart for Kubernetes
    digest: 6fcc59ac0d48edf35122994a707929c97ad8c26baf4161b3ac5460adf163bac8
    home: https://opentelemetry.io/
    icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
    maintainers:
    - name: dmitryax
    - name: jaronoff97
    - name: TylerHelmuth
    name: opentelemetry-collector
    sources:
    - https://github.com/open-telemetry/opentelemetry-collector
    - https://github.com/open-telemetry/opentelemetry-collector-contrib
    type: application
    urls:
    - https://MathTrail.github.io/charts/charts/opentelemetry-collector-0.145.0.tgz
    version: 0.145.0
  postgresql:
  - annotations:
      fips: "true"
      images: |
        - name: os-shell
          version: "5"
          image: registry-1.docker.io/bitnami/os-shell:latest
        - name: postgres-exporter
          version: 0.19.0
          image: registry-1.docker.io/bitnami/postgres-exporter:latest
        - name: postgresql
          version: 18.2.0
          image: registry-1.docker.io/bitnami/postgresql:latest
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 18.2.0
    created: "2026-02-15T22:50:19.361590127Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.36.0
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: 93d26702ef62441658193ae923ca60db636061205d04dbe78a15393fb41be749
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - https://MathTrail.github.io/charts/charts/postgresql-18.3.0.tgz
    version: 18.3.0
  pyroscope:
  - apiVersion: v2
    appVersion: 1.18.0
    created: "2026-02-15T22:50:19.400780402Z"
    dependencies:
    - alias: agent
      condition: agent.enabled
      name: grafana-agent
      repository: https://grafana.github.io/helm-charts
      version: 0.44.2
    - alias: alloy
      condition: alloy.enabled
      name: alloy
      repository: https://grafana.github.io/helm-charts
      version: 1.5.2
    - alias: minio
      condition: minio.enabled
      name: minio
      repository: https://charts.min.io/
      version: 4.1.0
    description: "\U0001F525 horizontally-scalable, highly-available, multi-tenant
      continuous profiling aggregation system"
    digest: e6b04ee6c05e6a6b33796cc3c46426710d68e2ed7dedfc53cee369048e75bef0
    home: https://grafana.com/oss/pyroscope/
    name: pyroscope
    sources:
    - https://github.com/grafana/pyroscope
    - https://github.com/grafana/pyroscope/tree/main/operations/pyroscope/helm/pyroscope
    type: application
    urls:
    - https://MathTrail.github.io/charts/charts/pyroscope-1.18.1.tgz
    version: 1.18.1
  redis:
  - annotations:
      fips: "true"
      images: |
        - name: kubectl
          version: 1.35.1
          image: registry-1.docker.io/bitnami/kubectl:latest
        - name: os-shell
          version: "5"
          image: registry-1.docker.io/bitnami/os-shell:latest
        - name: redis
          version: 8.6.0
          image: registry-1.docker.io/bitnami/redis:latest
        - name: redis-exporter
          version: 1.81.0
          image: registry-1.docker.io/bitnami/redis-exporter:latest
        - name: redis-sentinel
          version: 8.6.0
          image: registry-1.docker.io/bitnami/redis-sentinel:latest
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 8.6.0
    created: "2026-02-15T22:50:19.438164431Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.36.0
    description: Redis(R) is an open source, advanced key-value store. It is often
      referred to as a data structure server since keys can contain strings, hashes,
      lists, sets and sorted sets.
    digest: d827c4ce13a1b75a2776d7ae298b9c2031d21906d0ff89be7e075a2954e3fbe7
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: redis
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/redis
    urls:
    - https://MathTrail.github.io/charts/charts/redis-25.2.0.tgz
    version: 25.2.0
  strimzi-kafka-operator:
  - apiVersion: v2
    appVersion: 0.50.0
    created: "2026-02-15T22:50:19.506617706Z"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: 3dff5a4947584f4d124a701f28df180f7dd6a8bf4c963f7f375fdb28527059af
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - email: cncf-strimzi-maintainers@lists.cncf.io
      name: Strimzi Project Maintainers
      url: https://github.com/strimzi/governance
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - https://MathTrail.github.io/charts/charts/strimzi-kafka-operator-helm-3-chart-0.50.0.tgz
    version: 0.50.0
  telepresence-oss:
  - annotations:
      artifacthub.io/license: Apache-2.0
    apiVersion: v2
    appVersion: 2.26.2
    created: "2026-02-15T22:50:19.585893391Z"
    description: A chart for deploying the server-side components of Telepresence
    digest: 92647e39e46a93891ac6bc11880a608eea0a3d052ca1bbd4199207ab92d52745
    icon: https://raw.githubusercontent.com/telepresenceio/telepresence.io/master/src/assets/images/telepresence-edgy.svg
    keywords:
    - ambassador
    - telepresence
    - traffic-manager
    name: telepresence-oss
    sources:
    - https://github.com/telepresenceio/telepresence
    type: application
    urls:
    - https://MathTrail.github.io/charts/charts/telepresence-oss-2.26.2.tgz
    version: 2.26.2
generated: "2026-02-15T22:50:18.943880876Z"
