apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-script
  labels:
    {{- include "k6-test-runner.labels" . | nindent 4 }}
data:
  main.js: |
{{ .Values.loadTestScript | indent 4 }}
